name: QuickJoinMsg
author: TheDragonRing
version: 1.0.0
description: The simplest join message plugin around
api: 1.14.0
main: TheDragonRing\QuickJoinMsg\Main
load: STARTUP
commands:
    quickjoinmsg:
        usage: /quickjoinmsg
        description: View all the info about QuickJoinMsg, version, author, commands and permissions (alias = /qjm)
        aliases: qjm
        permission: quickjoinmsg.info
    setjoinmsg:
        usage: /setjoinmsg <message>
        description: Set custom join message (alias = sjm)
        aliases: sjm
        permission: quickjoinmsg.set
permissions:
    quickjoinmsg:
        default: op
            children:
                quickjoinmsg.info:
                    default: true
                quickjoinmsg.set:
                    default: op